vim.keymap.set("n", "<leader>gg", function()
    Snacks.lazygit()
end, { desc = "Lazygit" })
vim.keymap.set("n", "<leader>gf", function()
    Snacks.lazygit.log_file()
end, { desc = "Lazygit file log" })
vim.keymap.set("n", "<C-g>", function()
    Snacks.lazygit({ cwd = vim.fn.expand("%:p:h") })
end, { desc = "Lazygit (file dir)" })
