require("gitsigns").setup()
require("todo-comments").setup()

require("utility.autocmds")
require("utility.blink")
require("utility.conform")
require("utility.dap")
require("utility.diagnostics")
require("utility.oil")
require("utility.vim")
require("utility.snacks")
